import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import axonSvg from './illustrations/massing-axon.svg?raw'
import formSvg from './illustrations/building-form.svg?raw'

/**
 * BuildingForm — the real geometry of the complex, drawn from the
 * Bar Orian floor plates (lot 22). Two figures:
 *
 *   1. Site axonometric from the north-west street corner — true
 *      footprints (rounded corners on the north strip, stepped tower)
 *      with balconies recessed flush in the building line.
 *   2. North-elevation form diagram — the tower's three setbacks
 *      (floors 8 / 14 / 15) against the 7-floor boutique datum.
 *
 * SVGs are generated by scripts/build-massing-svg.mjs — regenerate
 * there, never hand-edit the .svg files.
 */
const BUILDING_LINKS = [
  { id: 'tower', he: 'מגדל הפארק', meta: '15 קומות · 3 נסיגות' },
  { id: 'boutique-n', he: 'מרקמי צפוני', meta: '3 בניינים · פינות מעוגלות' },
  { id: 'boutique-w', he: 'מרקמי מערבי', meta: '2 בניינים · 7 קומות' },
]

export default function BuildingForm() {
  return (
    <section className="bform" id="form" aria-label="הצורה האדריכלית של המתחם">
      <div className="bform-shell">
        <motion.span
          className="eyebrow bform-eyebrow"
          initial={{ opacity: 0, y: 10 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          — הצורה, במדויק
        </motion.span>

        <motion.h2
          className="bform-title"
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.4 }}
          transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
        >
          מצויר מהתוכניות. <em>לא מהדמיון.</em>
        </motion.h2>

        <motion.p
          className="bform-intro"
          initial={{ opacity: 0, y: 12 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.5 }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1], delay: 0.1 }}
        >
          האיורים האלה משורטטים ישירות מתוכניות ההגשה של בר אוריין — לא הדמיה
          חופשית. כך באמת ייראה המתחם: מרפסות שקועות בקו הבניין, גוף מדורג
          שנסוג בקומות 8, 14 ו־15, ופינות מעוגלות בבנייני הרחוב הצפוניים.
        </motion.p>

        <motion.figure
          className="bform-figure bform-axon"
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
        >
          <div
            className="bform-svg"
            // Generated, trusted, local SVG — see scripts/build-massing-svg.mjs
            dangerouslySetInnerHTML={{ __html: axonSvg }}
          />
          <figcaption>
            מבט אקסונומטרי מכיוון החצר הפנימית (דרום־מערב) · משורטט על־פי
            תוכנית ההעמדה של בר אוריין אדריכלים
          </figcaption>
        </motion.figure>

        <motion.figure
          className="bform-figure bform-elevation"
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
        >
          <div
            className="bform-svg"
            dangerouslySetInnerHTML={{ __html: formSvg }}
          />
          <figcaption>
            חתך צורני — נסיגות המגדל מול קו הגובה של בנייני הבוטיק
          </figcaption>
        </motion.figure>

        <div className="bform-links" role="list">
          {BUILDING_LINKS.map((b, idx) => (
            <motion.div
              key={b.id}
              role="listitem"
              initial={{ opacity: 0, y: 14 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.4 }}
              transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1], delay: idx * 0.08 }}
            >
              <Link
                to={`/catalog?building=${b.id}`}
                className="bform-link"
                aria-label={`${b.he} — לקטלוג הדירות`}
              >
                <span className="bform-link-title">{b.he}</span>
                <span className="bform-link-meta">{b.meta}</span>
                <ArrowLeft size={15} strokeWidth={1.5} aria-hidden="true" />
              </Link>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
